version: '3'

services:
  cloud-run-app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - WEB_SERVER_PORT=8080
      - WEATHER_API_KEY=ac7ecd1e7a7d4617bb9220959250704